-- Generated by bin/build-product-content.php
-- SEO content for the 89 products of the shooting catalogue

USE greenamal;

UPDATE products SET
  price = 49.00, stock = 30, status = 'active',
  description_short = 'Poudre dentaire blanchissante au charbon végétal et clous de girofle. Formulée dans le Moyen Atlas.',
  description_long = 'GreenSmile est notre poudre dentaire 100 % naturelle à base de charbon végétal actif et de clous de girofle moulus. Elle aide à blanchir l''émail en douceur, à apaiser les gencives et à neutraliser les mauvaises odeurs. Sans fluor, sans parabène, sans glycérine. Un pot suffit pour 2 mois d''utilisation quotidienne. Trempez votre brosse à dents humide dans la poudre et brossez normalement.',
  meta_title = 'Poudre dentaire blanchissante au charbon végétal et clous de giro',
  meta_description = 'GreenSmile est notre poudre dentaire 100 % naturelle à base de charbon végétal actif et de clous de girofle moulus. Elle aide à blanchir l''émail en douceur, à a',
  tags = 'poudre dentaire,charbon végétal,blanchissant,greensmile,naturel'
WHERE slug = 'greensmile-poudre-dentaire';

UPDATE products SET
  price = 55.00, stock = 30, status = 'active',
  description_short = 'Poudre de réglisse 100 % pure (60 g). Anti-pigmentaire, éclat naturel.',
  description_long = 'La poudre de réglisse pure est traditionnellement utilisée au Maroc pour unifier le teint et atténuer les taches pigmentaires. Riche en glabridine, elle ralentit la production de mélanine et révèle un éclat naturel. Mélangez une cuillère à café à votre masque ou à du yaourt pour le visage. Conservez au sec, à l''abri de la lumière.',
  meta_title = 'Poudre de réglisse 100 % pure (60 g). Anti-pigmentaire, éclat nat',
  meta_description = 'La poudre de réglisse pure est traditionnellement utilisée au Maroc pour unifier le teint et atténuer les taches pigmentaires. Riche en glabridine, elle ralenti',
  tags = 'réglisse moulu,anti-tache,glabridine,unifier teint'
WHERE slug = 'reglisse-moulu';

UPDATE products SET
  price = 49.00, stock = 30, status = 'active',
  description_short = 'Menthe pouliot moulue (70 g) — fraîcheur et purification du cuir chevelu.',
  description_long = 'La menthe pouliot (Mentha pulegium), surnommée "fliyo" au Maroc, est cueillie à l''état sauvage dans le Moyen Atlas. Sa poudre s''incorpore aux masques cheveux et au ghassoul pour purifier le cuir chevelu, apaiser les démangeaisons et apporter une fraîcheur tonifiante. Aussi en infusion digestive, à raison d''1 c. à café par tasse.',
  meta_title = 'Menthe pouliot moulue (70 g) — fraîcheur et purification du cuir ',
  meta_description = 'La menthe pouliot (Mentha pulegium), surnommée "fliyo" au Maroc, est cueillie à l''état sauvage dans le Moyen Atlas. Sa poudre s''incorpore aux masques cheveux et',
  tags = 'menthe pouliot,fliyo,cheveux,cuir chevelu,infusion'
WHERE slug = 'menthe-pouliot-poudre';

UPDATE products SET
  price = 65.00, stock = 30, status = 'active',
  description_short = 'Pétales de rose de Damas moulus (50 g). Soin visage anti-âge.',
  description_long = 'Issue des roseraies de Kelaat M''Gouna, notre poudre de rose conserve l''huile essentielle naturellement présente dans le pétale. Elle adoucit, hydrate et raffermit la peau. Idéale en masque hebdomadaire mélangée à du yaourt, du miel ou de l''argile blanche. Son parfum subtil dure des semaines après l''application.',
  meta_title = 'Pétales de rose de Damas moulus (50 g). Soin visage anti-âge.',
  meta_description = 'Issue des roseraies de Kelaat M''Gouna, notre poudre de rose conserve l''huile essentielle naturellement présente dans le pétale. Elle adoucit, hydrate et rafferm',
  tags = 'rose moulue,Damas,Kelaat,anti-âge,masque visage'
WHERE slug = 'rose-moulue';

UPDATE products SET
  price = 45.00, stock = 30, status = 'active',
  description_short = 'Origan moulu (70 g) — antiseptique naturel et exhausteur de saveur.',
  description_long = 'Cueilli dans les hauteurs du Moyen Atlas et séché à l''ombre, notre origan conserve toute sa puissance aromatique. Riche en carvacrol, il est traditionnellement utilisé contre les infections respiratoires et pour relever les marinades, pizzas, et viandes grillées. Son arôme intense en fait un incontournable de la cuisine méditerranéenne.',
  meta_title = 'Origan moulu (70 g) — antiseptique naturel et exhausteur de saveu',
  meta_description = 'Cueilli dans les hauteurs du Moyen Atlas et séché à l''ombre, notre origan conserve toute sa puissance aromatique. Riche en carvacrol, il est traditionnellement ',
  tags = 'origan,carvacrol,cuisine,antiseptique'
WHERE slug = 'origan-poudre';

UPDATE products SET
  price = 55.00, stock = 30, status = 'active',
  description_short = 'Berkoukch (couscous gros grain) 1 kg — la pâte rustique de l''Atlas.',
  description_long = 'Le berkoukch, ou "ml''igh", est un couscous à gros grains, roulé à la main par les femmes de la coopérative et séché au soleil. Plus rustique que la semoule fine, il se prête aux plats réconfortants en sauce, aux soupes et au "berkoukch aux légumes" traditionnel. Cuisson 15 min à la vapeur ou à l''eau frémissante.',
  meta_title = 'Berkoukch (couscous gros grain) 1 kg — la pâte rustique de l''Atla',
  meta_description = 'Le berkoukch, ou "ml''igh", est un couscous à gros grains, roulé à la main par les femmes de la coopérative et séché au soleil. Plus rustique que la semoule fine',
  tags = 'berkoukch,couscous gros grain,artisanal,Atlas,rustique'
WHERE slug = 'berkoukch';

UPDATE products SET
  price = 49.00, stock = 30, status = 'active',
  description_short = 'Couscous aux graines de lin 1 kg — riche en oméga 3.',
  description_long = 'Notre couscous aux graines de lin allie la tradition berbère à un apport nutritif moderne. Les graines de lin moulues s''incorporent à la semoule lors du roulage à la main. Source naturelle d''oméga 3, de fibres et de lignanes, il convient aux régimes santé sans renoncer au plaisir d''un couscous du vendredi.',
  meta_title = 'Couscous aux graines de lin 1 kg — riche en oméga 3.',
  meta_description = 'Notre couscous aux graines de lin allie la tradition berbère à un apport nutritif moderne. Les graines de lin moulues s''incorporent à la semoule lors du roulage',
  tags = 'couscous,graines de lin,oméga 3,santé,fibres'
WHERE slug = 'couscous-graines-lin';

UPDATE products SET
  price = 45.00, stock = 30, status = 'active',
  description_short = 'Couscous de maïs 1 kg — sans gluten, doux et coloré.',
  description_long = 'Roulé à la main avec de la semoule de maïs cultivée dans la région d''Ifrane, ce couscous offre une couleur dorée et une saveur douce, légèrement sucrée. Naturellement sans gluten, il accompagne agneau, légumes mijotés ou simplement un filet d''huile d''argan et de raisins secs.',
  meta_title = 'Couscous de maïs 1 kg — sans gluten, doux et coloré.',
  meta_description = 'Roulé à la main avec de la semoule de maïs cultivée dans la région d''Ifrane, ce couscous offre une couleur dorée et une saveur douce, légèrement sucrée. Naturel',
  tags = 'couscous maïs,sans gluten,doré,Ifrane'
WHERE slug = 'couscous-mais';

UPDATE products SET
  price = 49.00, stock = 30, status = 'active',
  description_short = 'Couscous parfumé à la sauge 1 kg — original et digestif.',
  description_long = 'Une création originale de la coopérative : la sauge fraîche du Moyen Atlas est intégrée à la semoule pendant le roulage. Le résultat est un couscous au parfum boisé et légèrement camphré, traditionnellement servi avec du poisson, du poulet aux herbes ou en accompagnement de tajines aux légumes verts.',
  meta_title = 'Couscous parfumé à la sauge 1 kg — original et digestif.',
  meta_description = 'Une création originale de la coopérative : la sauge fraîche du Moyen Atlas est intégrée à la semoule pendant le roulage. Le résultat est un couscous au parfum b',
  tags = 'couscous sauge,parfumé,herbes,digestif'
WHERE slug = 'couscous-sauge';

UPDATE products SET
  price = 45.00, stock = 30, status = 'active',
  description_short = 'Couscous d''orge 1 kg — la version berbère ancestrale.',
  description_long = 'Le couscous d''orge est la forme la plus ancienne et la plus traditionnelle au Maroc. Riche en fibres et à index glycémique bas, il a un goût rustique et robuste qui se marie particulièrement bien avec les sept légumes et les plats à base de viande de mouton. Roulé manuellement à partir d''orge cultivée localement.',
  meta_title = 'Couscous d''orge 1 kg — la version berbère ancestrale.',
  meta_description = 'Le couscous d''orge est la forme la plus ancienne et la plus traditionnelle au Maroc. Riche en fibres et à index glycémique bas, il a un goût rustique et robuste',
  tags = 'couscous orge,berbère,fibres,IG bas,traditionnel'
WHERE slug = 'couscous-orge';

UPDATE products SET
  price = 49.00, stock = 30, status = 'active',
  description_short = 'Couscous aux lentilles 1 kg — protéiné et complet.',
  description_long = 'Une innovation nutritive : la farine de lentilles moulues finement est incorporée à la semoule pour un couscous complet en protéines végétales. Idéal pour un plat unique équilibré, accompagné simplement de légumes vapeur et d''un filet d''huile d''olive.',
  meta_title = 'Couscous aux lentilles 1 kg — protéiné et complet.',
  meta_description = 'Une innovation nutritive : la farine de lentilles moulues finement est incorporée à la semoule pour un couscous complet en protéines végétales. Idéal pour un pl',
  tags = 'couscous lentilles,protéiné,complet,végétarien'
WHERE slug = 'couscous-lentilles';

UPDATE products SET
  price = 49.00, stock = 30, status = 'active',
  description_short = 'Couscous rouge 1 kg — couleur vive, goût intense.',
  description_long = 'Notre couscous rouge tire sa couleur d''un mélange de paprika doux et de poudre de tomate séchée incorporés au roulage. Saveur prononcée, idéal en accompagnement de poulet rôti, brochettes ou plats végétariens. Cuisson rapide à la vapeur.',
  meta_title = 'Couscous rouge 1 kg — couleur vive, goût intense.',
  meta_description = 'Notre couscous rouge tire sa couleur d''un mélange de paprika doux et de poudre de tomate séchée incorporés au roulage. Saveur prononcée, idéal en accompagnement',
  tags = 'couscous rouge,paprika,tomate,coloré'
WHERE slug = 'couscous-rouge';

UPDATE products SET
  price = 49.00, stock = 30, status = 'active',
  description_short = 'Couscous complet 1 kg — toute la fibre du grain entier.',
  description_long = 'Préparé avec de la semoule complète issue de blé dur non raffiné, ce couscous conserve le son et le germe du grain. Riche en fibres, magnésium et vitamines B, il a un goût plus rustique et un index glycémique plus bas que le couscous blanc classique.',
  meta_title = 'Couscous complet 1 kg — toute la fibre du grain entier.',
  meta_description = 'Préparé avec de la semoule complète issue de blé dur non raffiné, ce couscous conserve le son et le germe du grain. Riche en fibres, magnésium et vitamines B, i',
  tags = 'couscous complet,blé entier,fibres,IG bas'
WHERE slug = 'couscous-complet';

UPDATE products SET
  price = 55.00, stock = 30, status = 'active',
  description_short = 'Couscous khoumasi 1 kg — mélange aux 5 céréales.',
  description_long = 'Le "khoumasi" tire son nom du chiffre 5 en arabe : il combine cinq céréales (blé, orge, maïs, millet et lentilles) pour un profil nutritionnel complet. Une création de la coopérative qui offre une texture variée et un goût terroir profond, parfait pour qui veut redécouvrir le couscous différemment.',
  meta_title = 'Couscous khoumasi 1 kg — mélange aux 5 céréales.',
  meta_description = 'Le "khoumasi" tire son nom du chiffre 5 en arabe : il combine cinq céréales (blé, orge, maïs, millet et lentilles) pour un profil nutritionnel complet. Une créa',
  tags = 'couscous,khoumasi,5 céréales,nutrition,complet'
WHERE slug = 'couscous-khoumasi';

UPDATE products SET
  price = 45.00, stock = 30, status = 'active',
  description_short = 'Couscous de blé dur 1 kg — la semoule classique du vendredi.',
  description_long = 'La référence : couscous de blé dur roulé à la main, séché au soleil, prêt à cuire à la vapeur. Texture légère, grains réguliers, saveur neutre qui se marie avec tous les tajines, viandes et légumes. La semoule du couscous du vendredi traditionnel marocain.',
  meta_title = 'Couscous de blé dur 1 kg — la semoule classique du vendredi.',
  meta_description = 'La référence : couscous de blé dur roulé à la main, séché au soleil, prêt à cuire à la vapeur. Texture légère, grains réguliers, saveur neutre qui se marie avec',
  tags = 'couscous,blé dur,semoule,traditionnel'
WHERE slug = 'couscous-ble';

UPDATE products SET
  price = 49.00, stock = 30, status = 'active',
  description_short = 'Couscous aux herbes 1 kg — persil, menthe, coriandre.',
  description_long = 'Mélange d''herbes fraîches du Moyen Atlas (persil, coriandre, menthe pouliot) intégré au roulage. Couleur verte, parfum frais et digestif, idéal en plat froid type taboulé revisité ou tiède en accompagnement de poisson grillé.',
  meta_title = 'Couscous aux herbes 1 kg — persil, menthe, coriandre.',
  meta_description = 'Mélange d''herbes fraîches du Moyen Atlas (persil, coriandre, menthe pouliot) intégré au roulage. Couleur verte, parfum frais et digestif, idéal en plat froid ty',
  tags = 'couscous,herbes,persil,coriandre,menthe'
WHERE slug = 'couscous-herbes';

UPDATE products SET
  price = 39.00, stock = 30, status = 'active',
  description_short = 'Farine d''orge torréfiée 500 g — base traditionnelle de la zmita.',
  description_long = 'L''orge est légèrement torréfiée puis moulue à la pierre pour obtenir une farine au goût grillé caractéristique. Base de la "zmita" marocaine traditionnelle (mélange avec amande, miel, anis), elle se prépare aussi en bouillie réconfortante pour le petit-déjeuner ou en accompagnement de thé à la menthe.',
  meta_title = 'Farine d''orge torréfiée 500 g — base traditionnelle de la zmita.',
  meta_description = 'L''orge est légèrement torréfiée puis moulue à la pierre pour obtenir une farine au goût grillé caractéristique. Base de la "zmita" marocaine traditionnelle (mél',
  tags = 'farine orge torréfiée,zmita,traditionnel,petit-déjeuner'
WHERE slug = 'farine-orge-torrefiee';

UPDATE products SET
  price = 55.00, stock = 30, status = 'active',
  description_short = 'Talbina nabawiya 500 g — tradition prophétique apaisante.',
  description_long = 'La talbina est une bouillie d''orge mentionnée dans la tradition prophétique pour ses vertus apaisantes. Notre version respecte la recette traditionnelle : farine d''orge fine, à mélanger à de l''eau ou du lait et à laisser cuire à feu doux. Réconfortante, digestive, elle est traditionnellement consommée en cas de stress, fatigue ou deuil.',
  meta_title = 'Talbina nabawiya 500 g — tradition prophétique apaisante.',
  meta_description = 'La talbina est une bouillie d''orge mentionnée dans la tradition prophétique pour ses vertus apaisantes. Notre version respecte la recette traditionnelle : farin',
  tags = 'talbina,orge,sunna,prophétique,bouillie,apaisant'
WHERE slug = 'talbina-nabawiya';

UPDATE products SET
  price = 35.00, stock = 30, status = 'active',
  description_short = 'Farine de maïs 500 g — sans gluten, dorée.',
  description_long = 'Maïs cultivé dans la région d''Ifrane, séché et moulu à la pierre. Sans gluten, parfaite pour les pains, galettes type "harcha" et accompagnements traditionnels. Couleur jaune dorée, goût doux et légèrement sucré.',
  meta_title = 'Farine de maïs 500 g — sans gluten, dorée.',
  meta_description = 'Maïs cultivé dans la région d''Ifrane, séché et moulu à la pierre. Sans gluten, parfaite pour les pains, galettes type "harcha" et accompagnements traditionnels.',
  tags = 'farine maïs,sans gluten,harcha,doré'
WHERE slug = 'farine-mais';

UPDATE products SET
  price = 42.00, stock = 30, status = 'active',
  description_short = 'Farine de lentilles 500 g — riche en protéines.',
  description_long = 'Farine de lentilles moulues fraîchement, riche en protéines végétales (24 %) et en fer. Sans gluten, elle s''utilise pour épaissir des soupes (harira), faire des galettes salées ou enrichir les pâtes à pain et à pâtisserie. Excellent substitut pour les régimes sans gluten ou enrichis en protéines.',
  meta_title = 'Farine de lentilles 500 g — riche en protéines.',
  meta_description = 'Farine de lentilles moulues fraîchement, riche en protéines végétales (24 %) et en fer. Sans gluten, elle s''utilise pour épaissir des soupes (harira), faire des',
  tags = 'farine lentilles,protéines,sans gluten,fer,harira'
WHERE slug = 'farine-lentilles';

UPDATE products SET
  price = 39.00, stock = 30, status = 'active',
  description_short = 'Farine de blé torréfiée 500 g — saveur grillée caractéristique.',
  description_long = 'Blé dur légèrement torréfié avant mouture, ce qui développe une saveur grillée typique. Utilisée traditionnellement pour la "zmita" et certains pains rustiques, elle apporte une note caramélisée distinctive. À mélanger à du miel et de l''huile d''argan pour une collation énergétique authentique.',
  meta_title = 'Farine de blé torréfiée 500 g — saveur grillée caractéristique.',
  meta_description = 'Blé dur légèrement torréfié avant mouture, ce qui développe une saveur grillée typique. Utilisée traditionnellement pour la "zmita" et certains pains rustiques,',
  tags = 'farine blé torréfiée,zmita,grillé,traditionnel'
WHERE slug = 'farine-ble-torrefiee';

UPDATE products SET
  price = 39.00, stock = 30, status = 'active',
  description_short = 'Farine de maïs torréfiée 500 g — couleur ambrée, sans gluten.',
  description_long = 'Maïs torréfié puis moulu, plus aromatique que la farine de maïs classique. Sans gluten, idéale pour les bouillies, pains de maïs et galettes de fête. Apporte couleur ambrée et goût grillé distinctif.',
  meta_title = 'Farine de maïs torréfiée 500 g — couleur ambrée, sans gluten.',
  meta_description = 'Maïs torréfié puis moulu, plus aromatique que la farine de maïs classique. Sans gluten, idéale pour les bouillies, pains de maïs et galettes de fête. Apporte co',
  tags = 'farine maïs torréfiée,sans gluten,torréfié'
WHERE slug = 'farine-mais-torrefiee';

UPDATE products SET
  price = 45.00, stock = 30, status = 'active',
  description_short = 'Farine de pois chiches 500 g — protéinée, sans gluten.',
  description_long = 'Pois chiches du Maroc moulus finement. Très riche en protéines (22 %) et en fibres, elle permet de réaliser falafels, panisses, galettes et même la "panelle" méditerranéenne. Sans gluten, c''est aussi un excellent liant végétal pour remplacer les œufs en pâtisserie.',
  meta_title = 'Farine de pois chiches 500 g — protéinée, sans gluten.',
  meta_description = 'Pois chiches du Maroc moulus finement. Très riche en protéines (22 %) et en fibres, elle permet de réaliser falafels, panisses, galettes et même la "panelle" mé',
  tags = 'farine pois chiches,protéines,sans gluten,falafel'
WHERE slug = 'farine-pois-chiches';

UPDATE products SET
  price = 45.00, stock = 30, status = 'active',
  description_short = 'Farine de millet 500 g — céréale ancienne sans gluten.',
  description_long = 'Millet, céréale ancienne et rustique, moulu finement. Sans gluten, riche en magnésium et en silicium, il s''utilise pour bouillies, pains plats et pâtisseries. Goût doux et neutre, particulièrement adapté aux régimes spécifiques.',
  meta_title = 'Farine de millet 500 g — céréale ancienne sans gluten.',
  meta_description = 'Millet, céréale ancienne et rustique, moulu finement. Sans gluten, riche en magnésium et en silicium, il s''utilise pour bouillies, pains plats et pâtisseries. G',
  tags = 'farine millet,sans gluten,céréale ancienne,magnésium'
WHERE slug = 'farine-millet';

UPDATE products SET
  price = 39.00, stock = 30, status = 'active',
  description_short = 'Farine de blé complet 500 g — toute la fibre du grain.',
  description_long = 'Blé dur complet, moulu avec son et germe, pour une farine riche en fibres, vitamines B et minéraux. Parfaite pour pains rustiques, msemen complet, crêpes et pâtisseries plus nutritives. Goût plus prononcé que la farine raffinée, couleur dorée brun clair.',
  meta_title = 'Farine de blé complet 500 g — toute la fibre du grain.',
  meta_description = 'Blé dur complet, moulu avec son et germe, pour une farine riche en fibres, vitamines B et minéraux. Parfaite pour pains rustiques, msemen complet, crêpes et pât',
  tags = 'farine blé complet,fibres,B vitamines,pain rustique'
WHERE slug = 'farine-ble-complet';

UPDATE products SET
  price = 69.00, stock = 30, status = 'active',
  description_short = 'Eau florale de bleuet 200 ml — apaise les yeux et les peaux sensibles.',
  description_long = 'Distillée à partir de bleuets cultivés au Maroc, notre eau florale apaise les yeux fatigués (en compresse), décongestionne les paupières et calme les peaux sensibles ou irritées. Spray fin pour application directe ou sur coton. Sans alcool, sans conservateur. Conservation 12 mois après ouverture, au frais.',
  meta_title = 'Eau florale de bleuet 200 ml — apaise les yeux et les peaux sensi',
  meta_description = 'Distillée à partir de bleuets cultivés au Maroc, notre eau florale apaise les yeux fatigués (en compresse), décongestionne les paupières et calme les peaux sens',
  tags = 'eau florale bleuet,yeux,peau sensible,décongestionnant,hydrolat'
WHERE slug = 'eau-floral-bleuet';

UPDATE products SET
  price = 65.00, stock = 30, status = 'active',
  description_short = 'Eau florale de fleur d''oranger 200 ml — calmante et parfumée.',
  description_long = 'Distillée artisanalement à partir de fleurs d''oranger récoltées au printemps. Calmante pour la peau et les nerfs, elle s''utilise en pâtisserie marocaine (kaab el ghazal, msemen, thé), en spray rafraîchissant ou ajoutée au bain. Parfum subtil, légèrement sucré.',
  meta_title = 'Eau florale de fleur d''oranger 200 ml — calmante et parfumée.',
  meta_description = 'Distillée artisanalement à partir de fleurs d''oranger récoltées au printemps. Calmante pour la peau et les nerfs, elle s''utilise en pâtisserie marocaine (kaab e',
  tags = 'eau florale,fleur oranger,calmant,pâtisserie,hydrolat'
WHERE slug = 'eau-floral-fleur-oranger';

UPDATE products SET
  price = 69.00, stock = 30, status = 'active',
  description_short = 'Eau florale de rose 200 ml — tonifiante et anti-âge.',
  description_long = 'Pétales de rose de Damas distillés à la vapeur d''eau dans la pure tradition de Kelaat M''Gouna. Tonifie la peau, resserre les pores, ravive le teint et adoucit les rides. Aussi excellente en cuisine (pâtisseries, salades de fruits) et en lit de bouche pour rafraîchir la respiration.',
  meta_title = 'Eau florale de rose 200 ml — tonifiante et anti-âge.',
  meta_description = 'Pétales de rose de Damas distillés à la vapeur d''eau dans la pure tradition de Kelaat M''Gouna. Tonifie la peau, resserre les pores, ravive le teint et adoucit l',
  tags = 'eau florale rose,Damas,Kelaat,anti-âge,tonique'
WHERE slug = 'eau-floral-rose';

UPDATE products SET
  price = 65.00, stock = 30, status = 'active',
  description_short = 'Eau florale de camomille 200 ml — apaisante pour peaux réactives.',
  description_long = 'Camomille romaine distillée à basse température pour préserver les principes actifs. Apaise rougeurs, démangeaisons, coups de soleil et peaux atopiques. Convient aux bébés (sauf application contre-indiquée). Spray pratique, sans alcool, sans conservateur synthétique.',
  meta_title = 'Eau florale de camomille 200 ml — apaisante pour peaux réactives.',
  meta_description = 'Camomille romaine distillée à basse température pour préserver les principes actifs. Apaise rougeurs, démangeaisons, coups de soleil et peaux atopiques. Convien',
  tags = 'eau florale camomille,apaisant,peau réactive,bébé,hydrolat'
WHERE slug = 'eau-floral-camomille';

UPDATE products SET
  price = 89.00, stock = 30, status = 'active',
  description_short = 'GreenBoost 100 ml — distillat capillaire fortifiant aux herbes du Moyen Atlas.',
  description_long = 'GreenBoost est un distillat unique d''herbes du Moyen Atlas (romarin, jujubier, lavande, menthe, bleuet, rose, camomille, origan, pouliot) destiné à fortifier le cheveu et stimuler la pousse. Vaporisez sur le cuir chevelu propre, massez doucement, ne rincez pas. Utilisation quotidienne. Sans silicones, sans sulfates.',
  meta_title = 'GreenBoost 100 ml — distillat capillaire fortifiant aux herbes du',
  meta_description = 'GreenBoost est un distillat unique d''herbes du Moyen Atlas (romarin, jujubier, lavande, menthe, bleuet, rose, camomille, origan, pouliot) destiné à fortifier le',
  tags = 'greenboost,distillat,cheveu,fortifiant,pousse,herbes'
WHERE slug = 'greenboost';

UPDATE products SET
  price = 89.00, stock = 30, status = 'active',
  description_short = 'GreenEssence 30 ml — huile parfumée florale pour cheveux et corps.',
  description_long = 'Une eau de soin parfumée légère qui hydrate, parfume subtilement et soigne sans graisser. Idéale après la douche, en spray dans les cheveux ou sur le corps. Composée d''hydrolats et d''huiles essentielles dosées avec précision.',
  meta_title = 'GreenEssence 30 ml — huile parfumée florale pour cheveux et corps',
  meta_description = 'Une eau de soin parfumée légère qui hydrate, parfume subtilement et soigne sans graisser. Idéale après la douche, en spray dans les cheveux ou sur le corps. Com',
  tags = 'greenessence,huile parfumée,cheveux,corps,subtil'
WHERE slug = 'greenessence';

UPDATE products SET
  price = 99.00, stock = 30, status = 'active',
  description_short = 'GreenSilk 100 ml — huile post-épilation apaisante.',
  description_long = 'Mélange d''huiles précieuses (habat sawda, coco, argan, amande douce) et d''huile essentielle de lavande, GreenSilk apaise immédiatement la peau après épilation, réduit les rougeurs et prévient les poils incarnés. À appliquer en massage doux sur peau encore légèrement humide.',
  meta_title = 'GreenSilk 100 ml — huile post-épilation apaisante.',
  meta_description = 'Mélange d''huiles précieuses (habat sawda, coco, argan, amande douce) et d''huile essentielle de lavande, GreenSilk apaise immédiatement la peau après épilation, ',
  tags = 'greensilk,post-épilation,apaisant,argan,lavande'
WHERE slug = 'greensilk';

UPDATE products SET
  price = 79.00, stock = 30, status = 'active',
  description_short = 'Green Ritual Tabrima 100 g — gommage exfoliant aux plantes du Moyen Atlas.',
  description_long = 'Le tabrima est un rituel berbère de purification du corps. Notre version associe argile rouge, plantes broyées et huile d''argan pour exfolier en douceur tout en nourrissant. À utiliser en gommage hebdomadaire, sur peau humide, en mouvements circulaires. Rincer abondamment.',
  meta_title = 'Green Ritual Tabrima 100 g — gommage exfoliant aux plantes du Moy',
  meta_description = 'Le tabrima est un rituel berbère de purification du corps. Notre version associe argile rouge, plantes broyées et huile d''argan pour exfolier en douceur tout en',
  tags = 'tabrima,gommage,argile,plantes,argan,rituel'
WHERE slug = 'green-ritual-tabrima';

UPDATE products SET
  price = 55.00, stock = 30, status = 'active',
  description_short = 'Poudre de jujubier (sidr) 80 g — soin lavant des cheveux.',
  description_long = 'Le sidr (jujubier) est utilisé depuis des siècles comme shampooing naturel. Sa poudre lave en douceur sans agresser le cuir chevelu, gaine la fibre capillaire et apporte brillance. Mélangez à de l''eau tiède jusqu''à obtenir une pâte, appliquez sur cheveux mouillés, laissez poser 5 minutes, rincez.',
  meta_title = 'Poudre de jujubier (sidr) 80 g — soin lavant des cheveux.',
  meta_description = 'Le sidr (jujubier) est utilisé depuis des siècles comme shampooing naturel. Sa poudre lave en douceur sans agresser le cuir chevelu, gaine la fibre capillaire e',
  tags = 'jujubier,sidr,poudre lavante,cheveux,naturel'
WHERE slug = 'poudre-jujubier';

UPDATE products SET
  price = 69.00, stock = 30, status = 'active',
  description_short = 'Koumaj el jisem 175 g — gommage corps coloré au gravier de Fès.',
  description_long = 'Le "koumaj" est un mélange d''argile et d''huiles essentielles qui exfolie tout en raffermissant la peau. Notre version au gravier rouge de Fès (akkar fassi) et essences végétales apporte un soin spectaculaire en hammam. Utiliser sur peau mouillée, masser, laisser poser 2 minutes, rincer.',
  meta_title = 'Koumaj el jisem 175 g — gommage corps coloré au gravier de Fès.',
  meta_description = 'Le "koumaj" est un mélange d''argile et d''huiles essentielles qui exfolie tout en raffermissant la peau. Notre version au gravier rouge de Fès (akkar fassi) et e',
  tags = 'koumaj,gommage corps,akkar fassi,hammam'
WHERE slug = 'koumaj-jisem';

UPDATE products SET
  price = 69.00, stock = 30, status = 'active',
  description_short = 'Gommage au café 175 g — anti-cellulite et tonifiant.',
  description_long = 'Marc de café broyé fin associé à du sucre roux et à de l''huile de coco. Exfoliant tonifiant, il active la microcirculation, lisse l''aspect "peau d''orange" et laisse la peau douce et parfumée. À utiliser 1 à 2 fois par semaine sous la douche.',
  meta_title = 'Gommage au café 175 g — anti-cellulite et tonifiant.',
  meta_description = 'Marc de café broyé fin associé à du sucre roux et à de l''huile de coco. Exfoliant tonifiant, il active la microcirculation, lisse l''aspect "peau d''orange" et la',
  tags = 'gommage,café,anti-cellulite,exfoliant,tonifiant'
WHERE slug = 'gommage-cafe';

UPDATE products SET
  price = 69.00, stock = 30, status = 'active',
  description_short = 'Gommage au nila & huiles 175 g — peau lisse et lumineuse.',
  description_long = 'Le "nila" (indigo) est un trésor de la médecine traditionnelle marocaine : il purifie, apaise et illumine les peaux ternes. Notre gommage associe nila pur, sucre fin et un cocktail d''huiles précieuses (argan, sésame, jojoba). Idéal en cure pré-événement.',
  meta_title = 'Gommage au nila & huiles 175 g — peau lisse et lumineuse.',
  meta_description = 'Le "nila" (indigo) est un trésor de la médecine traditionnelle marocaine : il purifie, apaise et illumine les peaux ternes. Notre gommage associe nila pur, sucr',
  tags = 'nila,indigo,gommage,huiles,illuminant'
WHERE slug = 'gommage-nila-huiles';

UPDATE products SET
  price = 49.00, stock = 30, status = 'active',
  description_short = 'GreenRitual Savon bleu 200 g — savon noir au nila.',
  description_long = 'Notre savon noir Beldi traditionnel à l''huile d''olive, enrichi en nila. La couleur bleu-marine signe la richesse en pigment indigo, anti-inflammatoire et illuminant. À utiliser en hammam : appliquer, laisser poser 5 minutes, gommer au gant kessa, rincer.',
  meta_title = 'GreenRitual Savon bleu 200 g — savon noir au nila.',
  meta_description = 'Notre savon noir Beldi traditionnel à l''huile d''olive, enrichi en nila. La couleur bleu-marine signe la richesse en pigment indigo, anti-inflammatoire et illumi',
  tags = 'savon noir,Beldi,nila,hammam,gommage'
WHERE slug = 'greenritual-savon-bleu';

UPDATE products SET
  price = 49.00, stock = 30, status = 'active',
  description_short = 'GreenRitual Savon rose 200 g — savon noir aux pétales de rose.',
  description_long = 'Savon noir Beldi à base d''huile d''olive, infusé aux pétales de rose de Damas. Nettoie en profondeur tout en parfumant délicatement la peau. Texture onctueuse, fond douce et durable. Hammam ou douche quotidienne.',
  meta_title = 'GreenRitual Savon rose 200 g — savon noir aux pétales de rose.',
  meta_description = 'Savon noir Beldi à base d''huile d''olive, infusé aux pétales de rose de Damas. Nettoie en profondeur tout en parfumant délicatement la peau. Texture onctueuse, f',
  tags = 'savon noir,Beldi,rose,Damas,hammam'
WHERE slug = 'greenritual-savon-rose';

UPDATE products SET
  price = 49.00, stock = 30, status = 'active',
  description_short = 'GreenRitual Savon herbal 200 g — savon noir aux 7 plantes.',
  description_long = 'Notre savon noir Beldi enrichi d''un mélange de 7 plantes du Moyen Atlas (eucalyptus, romarin, lavande, menthe, thym, sauge, origan). Une expérience hammam complète : nettoie, parfume, vivifie. Texture épaisse traditionnelle.',
  meta_title = 'GreenRitual Savon herbal 200 g — savon noir aux 7 plantes.',
  meta_description = 'Notre savon noir Beldi enrichi d''un mélange de 7 plantes du Moyen Atlas (eucalyptus, romarin, lavande, menthe, thym, sauge, origan). Une expérience hammam compl',
  tags = 'savon noir,Beldi,7 plantes,hammam,herbal'
WHERE slug = 'greenritual-savon-herbal';

UPDATE products SET
  price = 85.00, stock = 30, status = 'active',
  description_short = 'GreenMoukhammaria 50 g — baume traditionnel multi-usage.',
  description_long = 'Le "moukhammaria" est un baume berbère traditionnel à base de cire d''abeille, beurre de karité et huiles essentielles, utilisé sur les lèvres, les coudes, les talons secs ou en application sur les piqûres d''insectes. Notre version en pot rose conserve la formule originale, fondante et parfumée.',
  meta_title = 'GreenMoukhammaria 50 g — baume traditionnel multi-usage.',
  meta_description = 'Le "moukhammaria" est un baume berbère traditionnel à base de cire d''abeille, beurre de karité et huiles essentielles, utilisé sur les lèvres, les coudes, les t',
  tags = 'moukhammaria,baume,karité,cire abeille,multi-usage'
WHERE slug = 'greenmoukhammaria';

UPDATE products SET
  price = 89.00, stock = 30, status = 'active',
  description_short = 'Huile essentielle de lavande vraie 15 ml — l''essentielle apaisante.',
  description_long = 'Distillée à la vapeur d''eau à partir de lavande cultivée dans le Moyen Atlas. L''huile essentielle la plus polyvalente : calme le stress, favorise le sommeil, apaise les piqûres, désinfecte les petites plaies. À diffuser, à diluer dans une huile végétale pour massage, ou en olfaction directe.',
  meta_title = 'Huile essentielle de lavande vraie 15 ml — l''essentielle apaisant',
  meta_description = 'Distillée à la vapeur d''eau à partir de lavande cultivée dans le Moyen Atlas. L''huile essentielle la plus polyvalente : calme le stress, favorise le sommeil, ap',
  tags = 'huile essentielle,lavande,sommeil,calmant,polyvalent'
WHERE slug = 'he-lavande';

UPDATE products SET
  price = 95.00, stock = 30, status = 'active',
  description_short = 'Huile essentielle de gingembre 15 ml — tonique et chauffant.',
  description_long = 'Issue de la racine de gingembre frais distillée. Tonifiante, anti-fatigue, elle réchauffe les muscles avant l''effort et soulage les nausées en olfaction. Antalgique en massage diluée à 5 % dans une huile végétale.',
  meta_title = 'Huile essentielle de gingembre 15 ml — tonique et chauffant.',
  meta_description = 'Issue de la racine de gingembre frais distillée. Tonifiante, anti-fatigue, elle réchauffe les muscles avant l''effort et soulage les nausées en olfaction. Antalg',
  tags = 'huile essentielle,gingembre,tonique,nausée,muscle'
WHERE slug = 'he-gingembre';

UPDATE products SET
  price = 85.00, stock = 30, status = 'active',
  description_short = 'Huile essentielle de menthe pouliot 15 ml — fraîcheur et concentration.',
  description_long = 'Menthe pouliot sauvage du Moyen Atlas distillée à basse pression. Stimule la concentration, dégage les voies respiratoires et apaise les maux de tête en application diluée sur les tempes. Usage modéré recommandé. Déconseillée femmes enceintes et enfants.',
  meta_title = 'Huile essentielle de menthe pouliot 15 ml — fraîcheur et concentr',
  meta_description = 'Menthe pouliot sauvage du Moyen Atlas distillée à basse pression. Stimule la concentration, dégage les voies respiratoires et apaise les maux de tête en applica',
  tags = 'huile essentielle,menthe pouliot,respiratoire,concentration'
WHERE slug = 'he-menthe-pouliot';

UPDATE products SET
  price = 85.00, stock = 30, status = 'active',
  description_short = 'Huile essentielle de romarin 1.8 cinéole 15 ml — circulation & cheveux.',
  description_long = 'Romarin de l''Atlas marocain à fort taux de 1.8 cinéole. Stimule la circulation sanguine, dynamise la pousse capillaire (en massage du cuir chevelu dilué dans une huile végétale) et clarifie l''esprit. À diffuser le matin pour bien démarrer la journée.',
  meta_title = 'Huile essentielle de romarin 1.8 cinéole 15 ml — circulation & ch',
  meta_description = 'Romarin de l''Atlas marocain à fort taux de 1.8 cinéole. Stimule la circulation sanguine, dynamise la pousse capillaire (en massage du cuir chevelu dilué dans un',
  tags = 'huile essentielle,romarin,cheveu,circulation,1.8 cinéole'
WHERE slug = 'he-romarin';

UPDATE products SET
  price = 89.00, stock = 30, status = 'active',
  description_short = 'Huile essentielle de menthe poivrée 15 ml — antalgique digestive.',
  description_long = 'Menthe poivrée distillée. Effet glaçon immédiat sur les coups, antalgique sur les maux de tête, digestive en olfaction ou ingestion (1 goutte sur sucre/miel). Très puissante : usage très modéré, déconseillée femmes enceintes/enfants <12 ans.',
  meta_title = 'Huile essentielle de menthe poivrée 15 ml — antalgique digestive.',
  meta_description = 'Menthe poivrée distillée. Effet glaçon immédiat sur les coups, antalgique sur les maux de tête, digestive en olfaction ou ingestion (1 goutte sur sucre/miel). T',
  tags = 'huile essentielle,menthe poivrée,digestif,antalgique'
WHERE slug = 'he-menthe-poivre';

UPDATE products SET
  price = 85.00, stock = 30, status = 'active',
  description_short = 'Huile essentielle d''eucalyptus globulus 15 ml — voies respiratoires.',
  description_long = 'Eucalyptus distillé en respect de la chémotype globulus. Décongestionnant respiratoire majeur en hiver, à diffuser, en inhalation, ou diluée en massage du thorax. Antibactérienne, expectorante. Dilution à 5 % minimum pour la peau.',
  meta_title = 'Huile essentielle d''eucalyptus globulus 15 ml — voies respiratoir',
  meta_description = 'Eucalyptus distillé en respect de la chémotype globulus. Décongestionnant respiratoire majeur en hiver, à diffuser, en inhalation, ou diluée en massage du thora',
  tags = 'huile essentielle,eucalyptus,globulus,respiratoire'
WHERE slug = 'he-eucalyptus';

UPDATE products SET
  price = 129.00, stock = 30, status = 'active',
  description_short = 'Huile essentielle de fleur d''oranger (néroli) 15 ml — précieuse et apaisante.',
  description_long = 'Le néroli est une huile précieuse — il faut près d''une tonne de fleurs pour produire 1 kg d''essence. Profondément calmante, anti-stress, anti-âge en cosmétique. À diffuser en cas d''anxiété ou diluée à 1 % dans un sérum visage.',
  meta_title = 'Huile essentielle de fleur d''oranger (néroli) 15 ml — précieuse e',
  meta_description = 'Le néroli est une huile précieuse — il faut près d''une tonne de fleurs pour produire 1 kg d''essence. Profondément calmante, anti-stress, anti-âge en cosmétique.',
  tags = 'huile essentielle,néroli,fleur oranger,anti-stress,précieuse'
WHERE slug = 'he-fleur-oranger';

UPDATE products SET
  price = 69.00, stock = 30, status = 'active',
  description_short = 'Huile essentielle de citron zeste 15 ml — purifiante et énergisante.',
  description_long = 'Zestes de citron pressés à froid. Tonifie l''organisme, purifie l''air ambiant en diffusion, soutient la digestion (1 goutte dans une cuillère de miel). Photosensibilisante : éviter l''application avant exposition au soleil.',
  meta_title = 'Huile essentielle de citron zeste 15 ml — purifiante et énergisan',
  meta_description = 'Zestes de citron pressés à froid. Tonifie l''organisme, purifie l''air ambiant en diffusion, soutient la digestion (1 goutte dans une cuillère de miel). Photosens',
  tags = 'huile essentielle,citron,zeste,énergisant,purifiant'
WHERE slug = 'he-citron';

UPDATE products SET
  price = 55.00, stock = 30, status = 'active',
  description_short = 'Pétales de rose séchés (alward) 50 g — décoration & infusion.',
  description_long = 'Pétales de rose de Damas du Moyen Atlas, séchés à l''ombre pour préserver couleur et arôme. À infuser pour une boisson tonique, à parsemer dans une salade ou un dessert, ou simplement à exposer dans un bol parfumé. Récolte de printemps.',
  meta_title = 'Pétales de rose séchés (alward) 50 g — décoration & infusion.',
  meta_description = 'Pétales de rose de Damas du Moyen Atlas, séchés à l''ombre pour préserver couleur et arôme. À infuser pour une boisson tonique, à parsemer dans une salade ou un ',
  tags = 'rose séchée,alward,Damas,infusion,décoration'
WHERE slug = 'pam-alward-rose';

UPDATE products SET
  price = 49.00, stock = 30, status = 'active',
  description_short = 'Clous de girofle 50 g — épice et antiseptique buccal.',
  description_long = 'Boutons floraux du giroflier, séchés. Indispensable des tajines, du ras el hanout et du thé d''hiver. Antiseptique buccal naturel : un clou mâché soulage les rages de dent. Conservation longue durée à l''abri de l''air.',
  meta_title = 'Clous de girofle 50 g — épice et antiseptique buccal.',
  meta_description = 'Boutons floraux du giroflier, séchés. Indispensable des tajines, du ras el hanout et du thé d''hiver. Antiseptique buccal naturel : un clou mâché soulage les rag',
  tags = 'girofle,épice,antiseptique,tajine'
WHERE slug = 'pam-girofle';

UPDATE products SET
  price = 55.00, stock = 30, status = 'active',
  description_short = 'Bleuet séché 20 g — tisane apaisante et déco florale.',
  description_long = 'Fleurs de bleuet (centaurea cyanus) cueillies puis séchées délicatement pour conserver leur bleu profond. À infuser pour une tisane apaisante des yeux et de la peau, ou à parsemer dans un mélange déco-pâtisserie.',
  meta_title = 'Bleuet séché 20 g — tisane apaisante et déco florale.',
  meta_description = 'Fleurs de bleuet (centaurea cyanus) cueillies puis séchées délicatement pour conserver leur bleu profond. À infuser pour une tisane apaisante des yeux et de la ',
  tags = 'bleuet,fleur séchée,tisane,décoration'
WHERE slug = 'pam-bleuet';

UPDATE products SET
  price = 69.00, stock = 30, status = 'active',
  description_short = 'GreenCalme — mélange apaisant 70 g (camomille, lavande, mélisse, menthe, marjolaine).',
  description_long = 'Notre mélange signature apaisant pour la fin de journée : camomille, lavande, mélisse, menthe pouliot, marjolaine et romarin. À infuser 5 minutes dans de l''eau chaude (1 c. à soupe par tasse). Aide à dénouer le stress, favoriser le sommeil et la digestion. Composition 100 % plantes du Moyen Atlas.',
  meta_title = 'GreenCalme — mélange apaisant 70 g (camomille, lavande, mélisse, ',
  meta_description = 'Notre mélange signature apaisant pour la fin de journée : camomille, lavande, mélisse, menthe pouliot, marjolaine et romarin. À infuser 5 minutes dans de l''eau ',
  tags = 'greencalme,tisane apaisante,sommeil,stress,mélange'
WHERE slug = 'pam-greencalme';

UPDATE products SET
  price = 35.00, stock = 30, status = 'active',
  description_short = 'Romarin séché 50 g — cuisine et tisane tonique.',
  description_long = 'Romarin officinal cueilli à la main puis séché à l''ombre. Aromate méditerranéen incontournable : viandes grillées, légumes rôtis, tajines. En infusion, il tonifie la mémoire et stimule la digestion.',
  meta_title = 'Romarin séché 50 g — cuisine et tisane tonique.',
  meta_description = 'Romarin officinal cueilli à la main puis séché à l''ombre. Aromate méditerranéen incontournable : viandes grillées, légumes rôtis, tajines. En infusion, il tonif',
  tags = 'romarin séché,herbe,tisane,cuisine'
WHERE slug = 'pam-romarin';

UPDATE products SET
  price = 45.00, stock = 30, status = 'active',
  description_short = 'Feuilles de jujubier 70 g — soin cheveux traditionnel.',
  description_long = 'Feuilles de jujubier (sidr) cueillies puis séchées entières. À broyer fraîchement pour usage cosmétique cheveux, ou à infuser pour une tisane purifiante.',
  meta_title = 'Feuilles de jujubier 70 g — soin cheveux traditionnel.',
  meta_description = 'Feuilles de jujubier (sidr) cueillies puis séchées entières. À broyer fraîchement pour usage cosmétique cheveux, ou à infuser pour une tisane purifiante.',
  tags = 'jujubier,sidr,feuille,cheveux,traditionnel'
WHERE slug = 'pam-jujubier';

UPDATE products SET
  price = 45.00, stock = 30, status = 'active',
  description_short = 'Lavande séchée 70 g — sommeil & parfum d''armoire.',
  description_long = 'Sommités fleuries de lavande coupées en bouquets et séchées. À glisser dans les armoires pour parfumer le linge, à infuser le soir pour apaiser, ou à utiliser en sachet sous l''oreiller pour favoriser le sommeil.',
  meta_title = 'Lavande séchée 70 g — sommeil & parfum d''armoire.',
  meta_description = 'Sommités fleuries de lavande coupées en bouquets et séchées. À glisser dans les armoires pour parfumer le linge, à infuser le soir pour apaiser, ou à utiliser e',
  tags = 'lavande séchée,sommeil,parfum armoire'
WHERE slug = 'pam-lavande';

UPDATE products SET
  price = 29.00, stock = 30, status = 'active',
  description_short = 'Menthe pouliot séchée (fliyo) 70 g — digestive du Moyen Atlas.',
  description_long = 'Menthe pouliot sauvage cueillie dans les hauteurs de l''Atlas. Très digestive en infusion après les repas. Note : déconseillée chez la femme enceinte. À utiliser modérément en cuisine.',
  meta_title = 'Menthe pouliot séchée (fliyo) 70 g — digestive du Moyen Atlas.',
  meta_description = 'Menthe pouliot sauvage cueillie dans les hauteurs de l''Atlas. Très digestive en infusion après les repas. Note : déconseillée chez la femme enceinte. À utiliser',
  tags = 'menthe pouliot,fliyo,tisane digestive'
WHERE slug = 'pam-menthe-pouliot';

UPDATE products SET
  price = 39.00, stock = 30, status = 'active',
  description_short = 'Camomille séchée 70 g — apaisante & sommeil.',
  description_long = 'Capitules floraux de camomille romaine séchés délicatement. La tisane d''avant-coucher par excellence : favorise le sommeil, apaise les troubles digestifs, calme l''anxiété. Aussi en compresse sur les yeux fatigués.',
  meta_title = 'Camomille séchée 70 g — apaisante & sommeil.',
  meta_description = 'Capitules floraux de camomille romaine séchés délicatement. La tisane d''avant-coucher par excellence : favorise le sommeil, apaise les troubles digestifs, calme',
  tags = 'camomille séchée,sommeil,digestif,apaisant'
WHERE slug = 'pam-camomille';

UPDATE products SET
  price = 35.00, stock = 30, status = 'active',
  description_short = 'Marjolaine séchée 70 g — herbe aromatique digestive.',
  description_long = 'Marjolaine (proche cousine de l''origan) cueillie puis séchée. Aromate doux et digestif, parfait dans les sauces tomate, les marinades et les viandes blanches. En tisane, elle calme les spasmes intestinaux.',
  meta_title = 'Marjolaine séchée 70 g — herbe aromatique digestive.',
  meta_description = 'Marjolaine (proche cousine de l''origan) cueillie puis séchée. Aromate doux et digestif, parfait dans les sauces tomate, les marinades et les viandes blanches. E',
  tags = 'marjolaine,herbe aromatique,digestif'
WHERE slug = 'pam-marjolaine';

UPDATE products SET
  price = 35.00, stock = 30, status = 'active',
  description_short = 'Sauge officinale séchée 70 g — antiseptique des sphères ORL.',
  description_long = 'Sauge officinale cueillie à la floraison, séchée à l''ombre. En gargarisme (infusion concentrée), elle soulage les maux de gorge. En cuisine, elle parfume les viandes blanches, le couscous, et les beurres.',
  meta_title = 'Sauge officinale séchée 70 g — antiseptique des sphères ORL.',
  meta_description = 'Sauge officinale cueillie à la floraison, séchée à l''ombre. En gargarisme (infusion concentrée), elle soulage les maux de gorge. En cuisine, elle parfume les vi',
  tags = 'sauge,gorge,gargarisme,cuisine'
WHERE slug = 'pam-sauge';

UPDATE products SET
  price = 49.00, stock = 30, status = 'active',
  description_short = 'Mélisse séchée 70 g — calme et digestif.',
  description_long = 'Mélisse officinale cueillie au matin pour préserver ses huiles essentielles. Tisane apaisante, anti-stress, calme les troubles digestifs liés à l''anxiété. Goût citronné caractéristique. Bonne complémentation avec la camomille en mélange.',
  meta_title = 'Mélisse séchée 70 g — calme et digestif.',
  meta_description = 'Mélisse officinale cueillie au matin pour préserver ses huiles essentielles. Tisane apaisante, anti-stress, calme les troubles digestifs liés à l''anxiété. Goût ',
  tags = 'mélisse,citron,calmant,digestif'
WHERE slug = 'pam-melisse';

UPDATE products SET
  price = 35.00, stock = 30, status = 'active',
  description_short = 'Thym séché 70 g — antiseptique respiratoire.',
  description_long = 'Thym sauvage de l''Atlas, plus parfumé que le thym commun, riche en thymol. En infusion, il combat efficacement rhumes, maux de gorge et toux. En cuisine, base des marinades et bouillons.',
  meta_title = 'Thym séché 70 g — antiseptique respiratoire.',
  meta_description = 'Thym sauvage de l''Atlas, plus parfumé que le thym commun, riche en thymol. En infusion, il combat efficacement rhumes, maux de gorge et toux. En cuisine, base d',
  tags = 'thym sauvage,thymol,respiratoire'
WHERE slug = 'pam-thym';

UPDATE products SET
  price = 49.00, stock = 30, status = 'active',
  description_short = 'Verveine séchée 50 g — l''infusion d''après-dîner.',
  description_long = 'Verveine officinale séchée doucement pour conserver son parfum citronné si reconnaissable. Digestive, légèrement sédative, c''est l''infusion d''après-dîner par excellence. Une cuillère par tasse, infusion 5 minutes.',
  meta_title = 'Verveine séchée 50 g — l''infusion d''après-dîner.',
  meta_description = 'Verveine officinale séchée doucement pour conserver son parfum citronné si reconnaissable. Digestive, légèrement sédative, c''est l''infusion d''après-dîner par ex',
  tags = 'verveine,citronné,digestif,tisane'
WHERE slug = 'pam-verveine';

UPDATE products SET
  price = 39.00, stock = 30, status = 'active',
  description_short = 'Eucalyptus séché 70 g — voies respiratoires.',
  description_long = 'Feuilles d''eucalyptus globulus séchées. À utiliser en inhalation pour décongestionner les voies respiratoires en hiver, ou en tisane (1 c. à café par tasse). Aussi à brûler pour assainir une pièce.',
  meta_title = 'Eucalyptus séché 70 g — voies respiratoires.',
  meta_description = 'Feuilles d''eucalyptus globulus séchées. À utiliser en inhalation pour décongestionner les voies respiratoires en hiver, ou en tisane (1 c. à café par tasse). Au',
  tags = 'eucalyptus,feuille,respiratoire,inhalation'
WHERE slug = 'pam-eucalyptus';

UPDATE products SET
  price = 69.00, stock = 30, status = 'active',
  description_short = 'Moringa séché 50 g — superfood riche en nutriments.',
  description_long = 'Feuilles de moringa oleifera, surnommé "arbre miraculeux" pour sa densité nutritionnelle exceptionnelle (vitamines A, C, calcium, fer, protéines). En infusion ou en poudre dans smoothies et soupes pour une cure énergisante.',
  meta_title = 'Moringa séché 50 g — superfood riche en nutriments.',
  meta_description = 'Feuilles de moringa oleifera, surnommé "arbre miraculeux" pour sa densité nutritionnelle exceptionnelle (vitamines A, C, calcium, fer, protéines). En infusion o',
  tags = 'moringa,superfood,vitamines,nutriment'
WHERE slug = 'pam-moringa';

UPDATE products SET
  price = 35.00, stock = 30, status = 'active',
  description_short = 'Origan séché 70 g — l''incontournable méditerranéen.',
  description_long = 'Origan sauvage du Moyen Atlas séché à l''ombre. Saveur intense, parfaite sur les pizzas, salades de tomates, marinades de poulet. En tisane, il soulage les voies respiratoires.',
  meta_title = 'Origan séché 70 g — l''incontournable méditerranéen.',
  meta_description = 'Origan sauvage du Moyen Atlas séché à l''ombre. Saveur intense, parfaite sur les pizzas, salades de tomates, marinades de poulet. En tisane, il soulage les voies',
  tags = 'origan séché,herbe,méditerranéen'
WHERE slug = 'pam-origan';

UPDATE products SET
  price = 79.00, stock = 30, status = 'active',
  description_short = 'Huile de massage 50 ml — détente musculaire et bien-être.',
  description_long = 'Mélange équilibré d''huiles végétales (sésame, amande douce, coco) et d''huiles essentielles relaxantes (lavande, marjolaine). Pénètre rapidement sans laisser de film gras, parfaite pour un massage du dos, des épaules ou des jambes lourdes.',
  meta_title = 'Huile de massage 50 ml — détente musculaire et bien-être.',
  meta_description = 'Mélange équilibré d''huiles végétales (sésame, amande douce, coco) et d''huiles essentielles relaxantes (lavande, marjolaine). Pénètre rapidement sans laisser de ',
  tags = 'huile massage,détente,lavande,relaxant'
WHERE slug = 'huile-massage';

UPDATE products SET
  price = 69.00, stock = 30, status = 'active',
  description_short = 'Huile de graines de lin 50 ml — riche en oméga 3.',
  description_long = 'Huile vierge de première pression à froid, à conserver au réfrigérateur après ouverture. Très haute concentration en oméga 3 (acide alpha-linolénique). À consommer crue uniquement, à raison d''une cuillère à soupe par jour, pour soutenir cœur, cerveau et inflammation.',
  meta_title = 'Huile de graines de lin 50 ml — riche en oméga 3.',
  meta_description = 'Huile vierge de première pression à froid, à conserver au réfrigérateur après ouverture. Très haute concentration en oméga 3 (acide alpha-linolénique). À consom',
  tags = 'huile lin,oméga 3,santé,cru'
WHERE slug = 'huile-graines-lin';

UPDATE products SET
  price = 89.00, stock = 30, status = 'active',
  description_short = 'Huile de rose musquée 50 ml — anti-âge cicatrisante.',
  description_long = 'Huile précieuse extraite des graines de rosier muscat. Riche en acides gras essentiels, vitamine A et antioxydants. Régénère les cellules, atténue les cicatrices et les vergetures, prévient le vieillissement cutané. Quelques gouttes en sérum visage le soir.',
  meta_title = 'Huile de rose musquée 50 ml — anti-âge cicatrisante.',
  meta_description = 'Huile précieuse extraite des graines de rosier muscat. Riche en acides gras essentiels, vitamine A et antioxydants. Régénère les cellules, atténue les cicatrice',
  tags = 'huile rose musquée,anti-âge,cicatrice,vergeture'
WHERE slug = 'huile-rose';

UPDATE products SET
  price = 89.00, stock = 30, status = 'active',
  description_short = 'Huile de jojoba 50 ml — l''huile équilibrante.',
  description_long = 'Cire liquide proche du sébum humain, le jojoba équilibre les peaux mixtes à grasses, hydrate sans graisser et démaquille en douceur. Aussi excellente sur cheveux secs (en bain d''huile) et pour adoucir le contour de l''œil.',
  meta_title = 'Huile de jojoba 50 ml — l''huile équilibrante.',
  meta_description = 'Cire liquide proche du sébum humain, le jojoba équilibre les peaux mixtes à grasses, hydrate sans graisser et démaquille en douceur. Aussi excellente sur cheveu',
  tags = 'jojoba,équilibrant,sébum,démaquillant'
WHERE slug = 'huile-jojoba';

UPDATE products SET
  price = 85.00, stock = 30, status = 'active',
  description_short = 'Huile de camomille 50 ml — apaisante peaux sensibles.',
  description_long = 'Macérat huileux de camomille dans une huile de tournesol bio. Apaise rougeurs, irritations, eczéma léger. Convient aux peaux ultra-sensibles et aux bébés. Application fine en massage doux ou en compresse.',
  meta_title = 'Huile de camomille 50 ml — apaisante peaux sensibles.',
  meta_description = 'Macérat huileux de camomille dans une huile de tournesol bio. Apaise rougeurs, irritations, eczéma léger. Convient aux peaux ultra-sensibles et aux bébés. Appli',
  tags = 'huile camomille,apaisant,peau sensible,bébé'
WHERE slug = 'huile-camomille';

UPDATE products SET
  price = 99.00, stock = 30, status = 'active',
  description_short = 'Huile d''argan à la fleur d''oranger 50 ml — soin parfumé.',
  description_long = 'Notre huile d''argan pure macérée délicatement avec des fleurs d''oranger pour un parfum subtil et envoûtant. Tous les bienfaits anti-âge de l''argan, plus une expérience sensorielle apaisante. Visage, corps, cheveux.',
  meta_title = 'Huile d''argan à la fleur d''oranger 50 ml — soin parfumé.',
  meta_description = 'Notre huile d''argan pure macérée délicatement avec des fleurs d''oranger pour un parfum subtil et envoûtant. Tous les bienfaits anti-âge de l''argan, plus une exp',
  tags = 'argan,fleur oranger,parfumé,anti-âge'
WHERE slug = 'huile-argan-fleur-oranger';

UPDATE products SET
  price = 55.00, stock = 30, status = 'active',
  description_short = 'Huile de sésame 50 ml — vierge première pression à froid.',
  description_long = 'Huile de sésame vierge extra, première pression à froid. Couleur ambrée, goût de noisette grillée. En cuisine pour parfumer salades et plats asiatiques, ou en cosmétique pour nourrir et protéger la peau (anti-UV léger).',
  meta_title = 'Huile de sésame 50 ml — vierge première pression à froid.',
  meta_description = 'Huile de sésame vierge extra, première pression à froid. Couleur ambrée, goût de noisette grillée. En cuisine pour parfumer salades et plats asiatiques, ou en c',
  tags = 'huile sésame,vierge,cuisine,cosmétique'
WHERE slug = 'huile-sesame';

UPDATE products SET
  price = 129.00, stock = 30, status = 'active',
  description_short = 'Huile d''argan 50 ml — l''or liquide du Maroc.',
  description_long = 'Première pression à froid, non torréfiée, pressée à la main par les femmes de la coopérative. Riche en vitamine E, oméga 6 et oméga 9. Nourrit la peau, fortifie cheveux et ongles, ralentit le vieillissement cutané. Quelques gouttes suffisent.',
  meta_title = 'Huile d''argan 50 ml — l''or liquide du Maroc.',
  meta_description = 'Première pression à froid, non torréfiée, pressée à la main par les femmes de la coopérative. Riche en vitamine E, oméga 6 et oméga 9. Nourrit la peau, fortifie',
  tags = 'argan,or liquide,vitamine E,anti-âge,Maroc'
WHERE slug = 'huile-argan';

UPDATE products SET
  price = 85.00, stock = 30, status = 'active',
  description_short = 'Huile de graine d''oignon 50 ml — anti-chute capillaire.',
  description_long = 'Huile macérée de graines d''oignon noir, traditionnellement utilisée au Maroc pour stimuler la pousse des cheveux et combattre la chute. Massage du cuir chevelu 2 fois par semaine, laisser poser 30 min minimum, rincer au shampoing doux.',
  meta_title = 'Huile de graine d''oignon 50 ml — anti-chute capillaire.',
  meta_description = 'Huile macérée de graines d''oignon noir, traditionnellement utilisée au Maroc pour stimuler la pousse des cheveux et combattre la chute. Massage du cuir chevelu ',
  tags = 'huile oignon,anti-chute,pousse cheveux'
WHERE slug = 'huile-graine-oignon';

UPDATE products SET
  price = 69.00, stock = 30, status = 'active',
  description_short = 'Huile d''amande amère 50 ml — peau et cheveux.',
  description_long = 'Macérat d''amandes amères. Adoucit la peau, atténue les vergetures et les cernes. En cuisine (avec parcimonie), parfume gâteaux et confiseries.',
  meta_title = 'Huile d''amande amère 50 ml — peau et cheveux.',
  meta_description = 'Macérat d''amandes amères. Adoucit la peau, atténue les vergetures et les cernes. En cuisine (avec parcimonie), parfume gâteaux et confiseries.',
  tags = 'amande amère,peau,vergetures'
WHERE slug = 'huile-amande-amere';

UPDATE products SET
  price = 75.00, stock = 30, status = 'active',
  description_short = 'Huile de romarin 50 ml — pousse capillaire.',
  description_long = 'Macérat huileux de romarin dans une huile d''olive vierge. Stimule la circulation du cuir chevelu et favorise la pousse capillaire. Massage en brosses énergiques 1 à 2 fois par semaine.',
  meta_title = 'Huile de romarin 50 ml — pousse capillaire.',
  meta_description = 'Macérat huileux de romarin dans une huile d''olive vierge. Stimule la circulation du cuir chevelu et favorise la pousse capillaire. Massage en brosses énergiques',
  tags = 'huile romarin,cuir chevelu,pousse cheveux'
WHERE slug = 'huile-romarin';

UPDATE products SET
  price = 99.00, stock = 30, status = 'active',
  description_short = 'Huile anti-chute 100 ml — synergie de 27 plantes & 15 huiles.',
  description_long = 'Notre formule signature anti-chute combine 27 extraits de plantes médicinales (jujubier, romarin, lavande, henné…) macérés dans 15 huiles végétales (argan, ricin, oignon, sésame, coco…). Massage du cuir chevelu, laisser poser 3 heures, shampoing doux. 1 à 2 fois par semaine.',
  meta_title = 'Huile anti-chute 100 ml — synergie de 27 plantes & 15 huiles.',
  meta_description = 'Notre formule signature anti-chute combine 27 extraits de plantes médicinales (jujubier, romarin, lavande, henné…) macérés dans 15 huiles végétales (argan, rici',
  tags = 'anti-chute,cheveu,plantes,signature,fortifiant'
WHERE slug = 'huile-anti-chute';

UPDATE products SET
  price = 85.00, stock = 30, status = 'active',
  description_short = 'Huile de graine noire (nigelle) 50 ml — la "guérisseuse" de la sunna.',
  description_long = 'Habat sawda — la nigelle — pressée à froid, non raffinée. Réputée pour ses vertus immuno-stimulantes (1 c. à café à jeun). Aussi en cosmétique pour les peaux à imperfections et les cheveux fragilisés. Tradition prophétique : "remède pour tout sauf la mort".',
  meta_title = 'Huile de graine noire (nigelle) 50 ml — la "guérisseuse" de la su',
  meta_description = 'Habat sawda — la nigelle — pressée à froid, non raffinée. Réputée pour ses vertus immuno-stimulantes (1 c. à café à jeun). Aussi en cosmétique pour les peaux à ',
  tags = 'nigelle,habat sawda,immunité,sunna'
WHERE slug = 'huile-graine-noire';

UPDATE products SET
  price = 69.00, stock = 30, status = 'active',
  description_short = 'Huile de lavande 50 ml — apaisante & cicatrisante.',
  description_long = 'Macérat huileux de fleurs de lavande dans une huile végétale neutre. Apaise les piqûres d''insectes, favorise la cicatrisation, calme la peau irritée. Parfum subtil, idéale en huile relaxante du soir.',
  meta_title = 'Huile de lavande 50 ml — apaisante & cicatrisante.',
  meta_description = 'Macérat huileux de fleurs de lavande dans une huile végétale neutre. Apaise les piqûres d''insectes, favorise la cicatrisation, calme la peau irritée. Parfum sub',
  tags = 'huile lavande,apaisant,cicatrisant'
WHERE slug = 'huile-lavande';

UPDATE products SET
  price = 199.00, stock = 30, status = 'active',
  description_short = 'Pack Talbina — talbina nabawiya, miel et fruits secs.',
  description_long = 'Notre coffret cadeau "Sunna" combine la talbina nabawiya (500 g), un pot de miel local et un sachet de fruits secs (figues, dattes, noix). Présenté dans une boîte cadeau soignée avec ruban. Idéal pour offrir à un proche en convalescence ou en signe de soin.',
  meta_title = 'Pack Talbina — talbina nabawiya, miel et fruits secs.',
  meta_description = 'Notre coffret cadeau "Sunna" combine la talbina nabawiya (500 g), un pot de miel local et un sachet de fruits secs (figues, dattes, noix). Présenté dans une boî',
  tags = 'pack,talbina,miel,cadeau,sunna'
WHERE slug = 'pack-talbina';

UPDATE products SET
  price = 449.00, stock = 30, status = 'active',
  description_short = 'Pack Cosmétique — la routine GreenAmal complète (7 produits).',
  description_long = 'Le coffret découverte de notre gamme cosmétique : GreenEssence (huile parfumée), GreenBoost (distillat capillaire), GreenSilk (post-épilation), Green Ritual Tabrima (gommage), GreenRitual Savon, GreenMoukhammaria (baume), et GreenSmile (poudre dentaire). Présenté dans une box élégante.',
  meta_title = 'Pack Cosmétique — la routine GreenAmal complète (7 produits).',
  meta_description = 'Le coffret découverte de notre gamme cosmétique : GreenEssence (huile parfumée), GreenBoost (distillat capillaire), GreenSilk (post-épilation), Green Ritual Tab',
  tags = 'pack,cosmétique,coffret,routine,découverte'
WHERE slug = 'pack-cosmetique';

UPDATE products SET
  price = 249.00, stock = 30, status = 'active',
  description_short = 'Pack 4 Eaux florales — Rose, Bleuet, Camomille, Fleur d''Oranger (4×200 ml).',
  description_long = 'Notre quatuor d''eaux florales (hydrolats) : Rose de Damas, Bleuet, Camomille romaine, Fleur d''Oranger. Pour la peau, les yeux, la cuisine et l''apaisement. Présenté en coffret cadeau avec sprays prêts à l''emploi.',
  meta_title = 'Pack 4 Eaux florales — Rose, Bleuet, Camomille, Fleur d''Oranger (',
  meta_description = 'Notre quatuor d''eaux florales (hydrolats) : Rose de Damas, Bleuet, Camomille romaine, Fleur d''Oranger. Pour la peau, les yeux, la cuisine et l''apaisement. Prése',
  tags = 'pack,eaux florales,hydrolat,coffret,quatuor'
WHERE slug = 'pack-eaux-florales';

UPDATE products SET
  price = 199.00, stock = 30, status = 'active',
  description_short = 'Pack Rose — la rose sous toutes ses formes.',
  description_long = 'Coffret thématique autour de la rose de Damas : eau florale (200 ml), pétales séchés (alward, 50 g), rose moulue (50 g), huile de rose musquée (50 ml). Pour soigner la peau, parfumer la cuisine et embellir le quotidien.',
  meta_title = 'Pack Rose — la rose sous toutes ses formes.',
  meta_description = 'Coffret thématique autour de la rose de Damas : eau florale (200 ml), pétales séchés (alward, 50 g), rose moulue (50 g), huile de rose musquée (50 ml). Pour soi',
  tags = 'pack,rose,Damas,coffret cadeau'
WHERE slug = 'pack-rose';

UPDATE products SET
  price = 349.00, stock = 30, status = 'active',
  description_short = 'Pack 8 Huiles essentielles — découverte aromathérapie.',
  description_long = 'Découvrez l''aromathérapie avec nos 8 huiles essentielles signature : Lavande, Romarin, Eucalyptus, Menthe poivrée, Menthe pouliot, Gingembre, Fleur d''oranger, Citron. Présentées en coffret bois avec compte-gouttes. Guide d''utilisation inclus.',
  meta_title = 'Pack 8 Huiles essentielles — découverte aromathérapie.',
  meta_description = 'Découvrez l''aromathérapie avec nos 8 huiles essentielles signature : Lavande, Romarin, Eucalyptus, Menthe poivrée, Menthe pouliot, Gingembre, Fleur d''oranger, C',
  tags = 'pack,huiles essentielles,aromathérapie,coffret'
WHERE slug = 'pack-huiles-essentielles';

UPDATE products SET
  price = 499.00, stock = 30, status = 'active',
  description_short = 'Pack 14 Huiles végétales — l''expérience GreenAmal.',
  description_long = 'Notre collection complète d''huiles végétales : argan, jojoba, rose musquée, sésame, lin, anti-chute, graine noire, et bien plus. Du soin capillaire au visage, de l''alimentation au massage : un essentiel pour qui aime les soins naturels.',
  meta_title = 'Pack 14 Huiles végétales — l''expérience GreenAmal.',
  meta_description = 'Notre collection complète d''huiles végétales : argan, jojoba, rose musquée, sésame, lin, anti-chute, graine noire, et bien plus. Du soin capillaire au visage, d',
  tags = 'pack,huiles végétales,collection,coffret'
WHERE slug = 'pack-huiles-vegetales';

UPDATE products SET
  price = 129.00, stock = 30, status = 'active',
  description_short = 'Pack 4 Poudres — Réglisse, Menthe pouliot, Rose, Origan.',
  description_long = 'Quartet de poudres végétales pour cuisine et cosmétique : réglisse moulu (60 g), menthe pouliot (70 g), rose moulue (50 g), origan moulu (70 g). Pour vos masques, infusions ou plats raffinés.',
  meta_title = 'Pack 4 Poudres — Réglisse, Menthe pouliot, Rose, Origan.',
  meta_description = 'Quartet de poudres végétales pour cuisine et cosmétique : réglisse moulu (60 g), menthe pouliot (70 g), rose moulue (50 g), origan moulu (70 g). Pour vos masque',
  tags = 'pack,poudres,quatuor,cosmétique'
WHERE slug = 'pack-poudres';

UPDATE products SET
  price = 129.00, stock = 30, status = 'active',
  description_short = 'Pack Gommage Café & Savon Beldi — rituel hammam.',
  description_long = 'Le duo essentiel de la routine hammam : Gommage au Café (175 g, anti-cellulite) et GreenRitual Savon Beldi (200 g). Pour une peau lisse, douce et tonifiée. Mode d''emploi dans la box.',
  meta_title = 'Pack Gommage Café & Savon Beldi — rituel hammam.',
  meta_description = 'Le duo essentiel de la routine hammam : Gommage au Café (175 g, anti-cellulite) et GreenRitual Savon Beldi (200 g). Pour une peau lisse, douce et tonifiée. Mode',
  tags = 'pack,gommage,savon,hammam,rituel'
WHERE slug = 'pack-gommage-cafe-savon';

UPDATE products SET
  price = 149.00, stock = 30, status = 'active',
  description_short = 'Pack Koumaj & Nila — duo gommage spectaculaire.',
  description_long = 'Notre duo gommage le plus puissant : Koumaj el Jisem (gravier de Fès) et Gommage au Nila (indigo) en 2×175 g. Pour une exfoliation complète et un éclat immédiat avant un événement.',
  meta_title = 'Pack Koumaj & Nila — duo gommage spectaculaire.',
  meta_description = 'Notre duo gommage le plus puissant : Koumaj el Jisem (gravier de Fès) et Gommage au Nila (indigo) en 2×175 g. Pour une exfoliation complète et un éclat immédiat',
  tags = 'pack,koumaj,nila,gommage'
WHERE slug = 'pack-koumaj-nila';

